version: "3"
services:
  wyl:
    image: aceberg/watchyourlan
    network_mode: "host"        
    restart: unless-stopped
    volumes:
    - /mnt/docker-storage/wyl:/data/WatchYourLAN
    environment:
      TZ: ${TZ}             # required: needs your TZ for correct time
      IFACES: "eth0"  # required: 1 or more interface
   #   HOST: ${swarm_ip}                   # optional, default: 0.0.0.0
      PORT: "8840"                      # optional, default: 8840
      TIMEOUT: "120"                    # optional, time in seconds, default: 120
      SHOUTRRR_URL: ""                  # optional, set url to notify
      THEME: "sand"                     # optional
      COLOR: "dark"                     # optional
    networks:
      - traefik-public
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.wyl.rule=Host(`lan`)'
        - 'traefik.http.services.wyl.loadbalancer.server.port=8840'
        - 'traefik.http.routers.wyl.entrypoints=web'
networks:
  traefik-public:
    external: true
