version: "3.8"

services:
  cup:
    image: ghcr.io/sergi0g/cup:latest
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.cup.rule=Host(`cup`)'
        - 'traefik.http.services.cup.loadbalancer.server.port=8000'
        - 'traefik.http.routers.cup.entrypoints=web'
        - homepage.group: Utilities
        - homepage.name: Cup
        - homepage.icon: /icons/cup-with-straw.png
        - homepage.href: http://swarm:8001
        - homepage.ping: http://swarm:8001
        - homepage.description: Checks for container updates
        - homepage.widget.type: customapi
        - homepage.widget.url: http://swarm:8001/api/v3/json
        - homepage.widget.mappings[0].label: Monitoring
        - homepage.widget.mappings[0].field.metrics: monitored_images
        - homepage.widget.mappings[0].format: number
        - homepage.widget.mappings[1].label: Up to date
        - homepage.widget.mappings[1].field.metrics: up_to_date
        - homepage.widget.mappings[1].format: number
        - homepage.widget.mappings[2].label: Updates
        - homepage.widget.mappings[2].field.metrics: updates_available
        - homepage.widget.mappings[2].format: number
    command: serve
    ports:
      - "8001:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker-storage/cup/cup.json:/config/cup.json
    networks:
      - traefik-public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    user: "0:0" 

networks:
  traefik-public:
    external: true
















