version: "3.8"

services:

  ##### Define the Cup Service #####
  cup:
    image: ghcr.io/sergi0g/cup:latest
    command: serve
    ##### Deployment Configuration #####
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3


    ##### Service Labels #####
      labels:
        - traefik.enable=true
        - traefik.http.routers.cup.rule=Host(`cup`)
        - traefik.http.services.cup.loadbalancer.server.port=8000
        - traefik.http.routers.cup.entrypoints=web

        - homepage.group=System Tools
        - homepage.name=Cup
        - homepage.icon=https://cdn3.iconfinder.com/data/icons/kitchen-45/512/neonsign_kitchen06-1024.png
        - homepage.href=http://cup/
        - homepage.description=Checks for container updates
        - "shepherd.watch=true"

    ##### Volume Mounts #####
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker-storage/cup/cup.json:/config/cup.json

    ##### Network Configuration #####
    networks:
      - traefik-public

    ##### Use a Non-Root User (update UID:GID as needed) #####
    user: "1000:996" # Replace with actual UID:GID from host for better security


networks:
  traefik-public:
    external: true
