version: "3.9" # Specifies the Docker Compose file format.

services:

  ##### Define the Kavita Service #####
  kavita:
    image: lscr.io/linuxserver/kavita:latest # Uses the latest Kavita image from LinuxServer.io.

    ##### Environment Configuration #####
    environment:
      - PUID=${PUID} # Sets the user ID for file permissions.
      - PGID=${PGID} # Defines the group ID to maintain proper access.
      - TZ=${TZ} # Configures the timezone setting for the container.

    ##### Persistent Storage Configuration #####
    volumes:
      - ${config}/kavita:/config:rw # Stores configuration files persistently.
      - ${media}:/data:rw # (Optional) Stores media content—ensure correct permissions.
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only access to the Docker socket for monitoring.

    ##### Port Mapping #####
    ports:
      - "5000:5000" # Maps container port 5000 to host port 5000 for external access.

    ##### Network Configuration #####
    networks:
      - traefik-public # Connects service to Traefik for reverse proxy management.

    ##### Deployment Configuration #####
    deploy:
      mode: replicated # Ensures the service can run multiple instances if needed.
      replicas: 1 # Runs a single instance—adjust for high availability if required.

      ##### Traefik Reverse Proxy Labels #####
      labels:
        # Traefik Reverse Proxy Labels
        - 'traefik.enable=true' # Enables Traefik for routing requests efficiently.
        - 'traefik.http.routers.kavita.rule=Host(`read`)' # Defines hostname routing within the network.
        - 'traefik.http.services.kavita.loadbalancer.server.port=5000' # Specifies the internal service port.
        - 'traefik.http.routers.kavita.entrypoints=web' # Uses HTTP entrypoint—consider HTTPS for security.


      ##### Homepage Dashboard Labels #####
        - homepage.group=Media # Groups service under "Media" in the dashboard.
        - homepage.name=Kavita # Sets the display name.
        - homepage.icon=kavita.png # Assigns a recognizable icon.
        - homepage.href=http://read/ # Provides direct access via dashboard.
        - homepage.description=Reader # Short description for dashboard entry.
        - homepage.weight=100 # Defines weight for ordering in dashboard.

      ##### Automated Updates #####
        - com.centurylinklabs.watchtower.enable="true" # Enables automatic updates via Watchtower.

    ##### Resource Constraints #####
      resources:
        limits:
          cpus: "0.50" # Limits CPU usage to prevent excessive resource consumption.
          memory: "512M" # Restricts memory usage to 512MB per instance.
        reservations:
          cpus: "0.25" # Guarantees at least 25% CPU availability.
          memory: "128M" # Ensures a baseline memory allocation for stability.

    ##### Restart Policy #####
      restart_policy:
        condition: on-failure # Ensures service restarts only if it crashes.
        delay: 5s # Waits 5 seconds before attempting a restart.
        max_attempts: 3 # Limits restart attempts to prevent infinite loops.
        window: 120s # Defines monitoring window for failure handling.

##### Network Definitions #####
networks:
  traefik-public:
    external: true # Uses an externally created Traefik network for service communication.
