version: "3.8"

services:

#### define the service ####
  drawio:
    image: jgraph/drawio:latest

### deployment criteria ####
    deploy:
      replicas: 1 # Specify the number of replicas for high availability
      restart_policy:
        condition: on-failure # Better restart control than 'restart: always'
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        # homepage dashboard labels
        - homepage.group=Productivity
        - homepage.name=Drawio
        - homepage.icon=draw-io.svg
        - homepage.href=http://10.0.0.20:8086/
        - homepage.description=drawing tool
        # simple traefik revers proxy labels
        - traefik.enable=true   #enable the use of traefik labels for routing.
        - traefik.http.routers.draw.rule=Host(`draw`)   #local dns setting
        - traefik.http.routers.draw.entrypoints=web
        - traefik.http.services.draw.loadbalancer.server.port=8086 

#### set resource limits ####
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "128M"

#### assign a free port #####          
    ports:
      - "8086:8080"

#### use traefik network for local reverse proxy      
    networks:
      - traefik-public
    environment:
      DRAWIO_HOME: "/data" # Example environment variable for customization
    volumes:
      - /mnt/docker-storage/drawio:/data:rw # Persistent storage for data

networks:
  traefik-public:
    external: true
