---
services:
  mysql:
    image: mysql:latest
    networks:
      - backend-netwk
    volumes:
      - /mnt/docker-storage/piwigo/sql-data1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${root_pswrd}
      MYSQL_DATABASE: db
      MYSQL_USER: piwigo
      MYSQL_PASSWORD: ${pswrd}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /mnt/docker-storage/piwigo:/config
      - /mnt/nfs/data/gallery:/gallery
    ports:
      - 89:80
    restart: unless-stopped
    networks:
      - traefik-public
      - backend-netwk
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.piwigo.rule=Host(`pics`)'
        - 'traefik.http.services.piwigo.loadbalancer.server.port=89'
        - 'traefik.http.routers.piwigo.entrypoints=web'
    depends_on:
      - mysql
volumes:
  sql-data1:
      
networks:
  backend-netwk:
    external: true
  traefik-public:
    external: true
