services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8989:8989
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${config}/sonarr:/config
      - ${media}/tv:/tv
      - ${data}:/data
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.sonarr.rule=Host(`sonarr`)'
        - 'traefik.http.services.sonarr.loadbalancer.server.port=8989'
        - 'traefik.http.routers.sonarr.entrypoints=web'
        - homepage.group=Media
        - homepage.name=Sonarr
        - homepage.icon=sonarr.png
        - homepage.href=http://sonarr
        - homepage.description=Tv
networks:
  traefik-public:
    external: true


