version: "3.8"

configs:
  sonarr_env:
    external: true

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      ##### Reverse Proxy Labels for Traefik #####
      labels:
        - "traefik.enable=true" # Enables Traefik service routing.
        - "traefik.http.routers.sonarr.rule=Host(`sonarr`)" # Uses hostname-based routing—update as needed.
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989" # Specifies service port for Traefik load balancing.
        - "traefik.http.routers.sonarr.entrypoints=web" # Uses HTTP entrypoint—consider enabling HTTPS for security.

      ##### Homepage Dashboard Labels #####
        - "homepage.group=Media" # Groups service under "Media" in the dashboard.
        - "homepage.name=Sonarr" # Sets display name for easy identification.
        - "homepage.icon=sonarr.png" # Assigns a recognizable icon.
        - "homepage.href=http://sonarr/" # Provides direct access via the dashboard.
        - "homepage.description=TV Shows" # Short description for dashboard entry.
        - "homepage.weight=1" # Defines weight for ordering in the dashboard.

      ##### Automated Updates #####
        - "com.centurylinklabs.watchtower.enable=true" # Enables automatic updates via Watchtower.

    environment:
      - PUID_FILE=/run/secrets/host_env
      - PGID_FILE=/run/secrets/host_env
      - TZ_FILE=/run/secrets/host_env
    configs:
      - source: host_env
        target: /run/secrets/host_env
    volumes:
      - type: bind
        source: /mnt/docker-storage/sonarr
        target: /config
      - type: bind
        source: /mnt/nfs/data
        target: /media
      - type: bind
        source: /mnt/nfs/torrents
        target: /data
    networks:
      - traefik-public
    ports:
      - target: 8989
        published: 8989
        protocol: tcp
        mode: host

       # Connects Sonarr to the Traefik reverse proxy for secure routing.

    ##### Deployment Configuration #####
    
##### Network Definitions #####
networks:
  traefik-public:
    external: true # Uses an externally created Traefik network for reverse proxy integration.
