version: "3.9"
services:
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    deploy:
      labels:
        - homepage.group=Servarr
        - homepage.name=tunnel
        - homepage.icon=cloudflared.png
        - homepage.description=secure tunnel
      replicas: 2
    networks:
      - frontend-ntwk
    environment:
      - TUNNEL_TOKEN=${cftoken}
networks:
    frontend-ntwk:
      external: true
