version: "3.9
services:
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    deploy:
      replicas: 2
      labels:
        - homepage.group=Web
        - homepage.name=Cloudflare tunnel
        - homepage.icon=cloudflare.png
        - homepage.description=Secure tunnel
        - com.centurylinklabs.watchtower.enable="true"
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/TUNNEL_TOKEN
    secrets:
      - TUNNEL_TOKEN
    networks:
      - frontend-ntwk
secrets:
  TUNNEL_TOKEN:
    external: true

networks:
  frontend-ntwk:
    external: true

