version: "3.9"
services:
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    deploy:
      labels:
        - homepage.group=Web
        - homepage.name=tunnel
        - homepage.icon=cloudflare.png
        - homepage.description=secure tunnel
      replicas: 2
    networks:
      - frontend-ntwk
    environment:
      - TUNNEL_TOKEN_file= /run/secrets/tunneltoken
    secrets:
      - tunneltoken

secrets:
   tunneltoken:
     external: true
networks:
    frontend-ntwk:
      external: true
