version: "3.9"
services:
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"
      labels:
        - homepage.group=Web
        - homepage.name=Cloudflare tunnel
        - homepage.icon=cloudflare.png
        - homepage.description=Secure tunnel
        - com.centurylinklabs.watchtower.enable: "true"
      replicas: 2
    networks:
      - frontend-ntwk
    environment:
      - TUNNEL_TOKEN_FILE=/run/secrets/TUNNEL_TOKEN
    secrets:
      - TUNNEL-TOKEN

secrets:
   TUNNEL_TOKEN:
     external: true
networks:
    frontend-ntwk:
      external: true
