version: '3'

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      ADVERTISE_IP: 'http://10.0.0.20:32400/'
      PLEX_CLAIM: 'claim-JdvxqJH71jc1wYbJbh2L'
      TZ: 'America/Vancouver'
    volumes:
      - /mnt/docker-storage/plex:/config
      - /mnt/docker-storage/plex/plex_transcode:/transcode
      - /mnt/nfs/data:/data
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.http.routers.plex.rule=Host(`plex`)"
        - "traefik.http.services.plex.loadbalancer.server.port=32400"
        - "traefik.enable=true"
networks:
  traefik-public:
    external: true




