services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-storage/readarr:/config
      - /mnt/nfs/data/books:/books
      - /mnt/nfs/torrents:/data
    restart: unless-stopped
    ports:
      - 8787:8787
    networks:
      - traefik-public
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.readarr.rule=Host(`readarr`)'
        - 'traefik.http.services.readarr.loadbalancer.server.port=8787'
        - 'traefik.http.routers.readarr.entrypoints=web'
networks:
  traefik-public:
    external: true
