version: '3.8'
services:
  mysql:
    image: mysql:latest
    networks:
      - backend-ntwk
    volumes:
      - /mnt/docker-storage/wordpress/sql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my.pswrd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: pswrd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    networks:
      - frontend-ntwk
      - backend-ntwk
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: pswrd
      WORDPRESS_DB_NAME: wordpress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql

volumes:
  sql-data:

networks:
  backend-ntwk:
    external: true
  frontend-ntwk:
    external: true
