version: "3.9"

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - trtaefik-public
    volumes:
      - /mnt/docker-storage/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /mnt/docker-storage/caddy/data:/data
      - /mnt/docker-storage/caddy/config:/config
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"

networks:
  traefik-public:
    external: true

