services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    environment:
      - PUID=${PUID}
      - PGID=$PGID}
      - TZ=${TZ}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${config}/readarr:/config
      - ${media}/books:/books
      - ${data}:/data
    restart: unless-stopped
    ports:
      - 8787:8787
    networks:
      - traefik-public
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.readarr.rule=Host(`readarr`)'
        - 'traefik.http.services.readarr.loadbalancer.server.port=8787'
        - 'traefik.http.routers.readarr.entrypoints=web'
        - homepage.group=Media
        - homepage.name=Readarr
        - homepage.icon=readarr.png
        - homepage.href=http://readarr/
        - homepage.description=books
networks:
  traefik-public:
    external: true
