version: "3.9" # Specifies the Docker Compose file format.

services:

  ##### Define the Prowlarr Indexing Service #####
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest # Uses the latest Prowlarr image—pin to a specific version if needed.

    ##### Environment Configuration #####
    environment:
      - PUID=${PUID} # Defines user permissions for accessing files.
      - PGID=${PGID} # Specifies group permissions to maintain consistent access control.
      - TZ=${TZ} # Configures timezone settings for logging and scheduling.

    ##### Persistent Storage Configuration #####
    volumes:
      - ${config}/prowlarr:/config:rw # Stores configuration files persistently for data retention.

    ##### Port Mapping #####
    ports:
      - "9696:9696" # Maps container port 9696 to host port 9696 for external access.

    ##### Network Configuration #####
    networks:
      - traefik-public # Connects service to Traefik reverse proxy for secure routing.

    ##### Deployment Configuration #####
    deploy:
      mode: replicated # Allows for multiple instances if scaling is required.
      replicas: 1 # Runs a single instance—adjust for high availability.

      ##### Service Labels #####
      labels:
        # Traefik Reverse Proxy Labels
        - 'traefik.enable=true' # Enables Traefik service routing.
        - 'traefik.http.routers.prowlarr.rule=Host(`prowlarr`)' # Uses hostname-based routing—update as needed.
        - 'traefik.http.services.prowlarr.loadbalancer.server.port=9696' # Specifies service port for Traefik load balancing.
        - 'traefik.http.routers.prowlarr.entrypoints=web' # Uses HTTP entrypoint—consider HTTPS for security.

        # Homepage Dashboard Labels
        - 'homepage.group=Media' # Groups service under "Media" in the dashboard.
        - 'homepage.name=Prowlarr' # Sets display name for easy identification.
        - 'homepage.icon=prowlarr.png' # Assigns a recognizable icon.
        - 'homepage.href=http://prowlarr/' # Provides direct access via dashboard—ensure hostname resolution.
        - 'homepage.description=Indexers' # Brief service description.
        - homepage.weight=6 # Defines weight for ordering in the dashboard.

        # Automated Updates
        - com.centurylinklabs.watchtower.enable="true" # Enables automatic updates via Watchtower.

    ##### Restart Policy #####
      restart_policy:
        condition: on-failure # Restarts service only if it crashes.
        delay: 5s # Waits 5 seconds before retrying.
        max_attempts: 3 # Limits restart attempts to prevent infinite loops.

    ##### Resource Constraints #####
      resources:
        limits:
          cpus: "0.50" # Restricts CPU usage to prevent resource exhaustion.
          memory: "256M" # Caps memory usage at 256MB per instance.
        reservations:
          cpus: "0.25" # Guarantees at least 25% CPU availability.
          memory: "128M" # Ensures a baseline memory allocation for stability.

##### Network Definitions #####
networks:
  traefik-public:
    external: true # Uses an externally defined Traefik network for reverse proxying and service communication.
