version: '3'

services:
  traefik:
    image: traefik:v3.1
    hostname: '{{.Node.Hostname}}'
    ports:
      - target: 80
        published: 80
        protocol: tcp
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.dashboard=true
      - --log.level=INFO
      - --accesslog=true
      - --providers.swarm.exposedByDefault=false
      - --providers.swarm.network=traefik-public
      - --entrypoints.web.address=:80
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.main ==true
      labels:
        - traefik.enable=true
        - traefik.http.routers.mydashboard.rule=Host(`traefik`)
        - traefik.http.routers.mydashboard.service=api@internal
        - traefik.http.services.mydashboard.loadbalancer.server.port=1337
        - homepage.group=Servarr
        - homepage.name=Traefik
        - homepage.icon=traefik.png
        - homepage.href=http://traefik/
        - homepage.description= proxy
  whoami:
    image: traefik/whoami:v1.10
    hostname: '{{.Node.Hostname}}'
    networks:
      - traefik-public
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.rule=Host(`whoami`)
        - traefik.http.services.whoami.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
