version: '3'

services:
  traefik:
    image: traefik:v3.1
    hostname: '{{.Node.Hostname}}'
    ports:
      # listen on host ports without ingress network
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - traefik-public
    environment:
      # vars depend on your DNS provider
     - CF_API_EMAIL=${CF_API_EMAIL}
     - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker-storage/traefik/certs:/certificates
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-storage/traefik/traefik.yml:/traefik.yml:ro
      - /mnt/docker-storage/traefik/acme.json:/acme.json
      - /mnt/docker-storage/traefik/config.yml:/config.ym
    deploy:
      mode: global
      placement:
        constraints:
          - node.role==manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.mydashboard.rule=Host(`traefik,traefik.stevenfmeyer.me`)
        - traefik.http.routers.mydashboard.service=api@internal
        - traefik.http.services.mydashboard.loadbalancer.server.port=1337
        - homepage.group=Servarr
        - homepage.name=Traefik
        - homepage.icon=traefik.png
        - homepage.href=http://traefik/
        - homepage.description= proxy

  whoami:
    image: traefik/whoami:v1.10
    hostname: '{{.Node.Hostname}}'
    networks:
      - traefik-public
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.rule=Host(`whoami`)
        - traefik.http.services.whoami.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
volumes:
  letsencrypt:
    name: letsencrypt

