version: '3.9'

services:
  plex:
    image: plexinc/pms-docker:1.25.0 # Pin the version for stability
    environment:
      ADVERTISE_IP: ${swarm_ip}:32400
      PLEX_CLAIM: ${claim}
      TZ: ${TZ}
    volumes:
      - ${config}/plex:/config:rw
      - ${config}/plex/plex_transcode:/transcode:rw
      - ${media}:/data:ro
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1 # Adjust as needed for scaling
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.plex.rule=Host(`plexswarm`)"
        - 'traefik.http.routers.lidarr.entrypoints=web'
        - "traefik.http.services.plex.loadbalancer.server.port=32400"
        - homepage.group=Media
        - homepage.name=Plex
        - homepage.icon=plex.png
        - homepage.href=http://swarm:32400/web
        - homepage.description=Media server
        - homepage.weight=100
        - com.centurylinklabs.watchtower.enable="true"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: "1.00"
          memory: "2G"
        reservations:
          cpus: "0.50"
          memory: "1G"

networks:
  traefik-public:
    external: true
