version: "3.9" # Specifies the Docker Compose file format.

services:

  ##### Define the Plex Media Server #####
  plex:
    image: plexinc/pms-docker:1.25.0 # Uses a pinned version for stability—update as needed.

    ##### Environment Configuration #####
    environment:
      ADVERTISE_IP: ${swarm_ip}:32400 # Ensures Plex announces its IP properly in a swarm setup.
      PLEX_CLAIM: ${claim} # Allows automatic server claim for linking Plex to an account.
      TZ: ${TZ} # Configures timezone for consistent logging and scheduling.

    ##### Persistent Storage Configuration #####
    volumes:
      - ${config}/plex:/config:rw # Stores Plex configuration and metadata.
      - ${config}/plex/plex_transcode:/transcode:rw # Defines a separate transcode directory for optimized performance.
      - ${media}:/data:ro # Read-only access to media storage—ensure correct permissions.

    ##### Port Mapping #####
    ports:
      - 32400:32400/tcp # Web interface and API communication.
      - 8324:8324/tcp # Plex Companion remote access.
      - 32469:32469/tcp # DLNA server communication.
      - 1900:1900/udp # DLNA discovery.
      - 32410:32410/udp # GDM network discovery.
      - 32412:32412/udp # Plex multicast communication.
      - 32413:32413/udp # Additional multicast support.
      - 32414:32414/udp # Secondary multicast channel.

    ##### Network Configuration #####
    networks:
      - traefik-public # Connects Plex to the Traefik reverse proxy network.

    ##### Deployment Configuration #####
    deploy:
      mode: replicated # Ensures the service can run multiple instances if needed.
      replicas: 1 # Runs a single instance—adjust for high availability.

      ##### Reverse Proxy Labels for Traefik #####
      labels:
        - "traefik.enable=true" # Enables Traefik for routing requests efficiently.
        - "traefik.http.routers.plex.rule=Host(`plexswarm`)" # Defines hostname routing within the network.
        - "traefik.http.services.plex.loadbalancer.server.port=32400" # Specifies the internal service port for load balancing.

      ##### Homepage Dashboard Labels #####
        - homepage.group=Media # Groups Plex under "Media" in the dashboard.
        - homepage.name=Plex # Sets display name for easy identification.
        - homepage.icon=plex.png # Assigns an icon for recognition.
        - homepage.href=http://swarm:32400/web # Provides direct access via dashboard.
        - homepage.description=Media server # Short description for dashboard entry.
        - homepage.weight=100 # Defines weight for ordering in dashboard.

      ##### Automated Updates #####
        - com.centurylinklabs.watchtower.enable="true" # Enables automatic updates via Watchtower.

    ##### Restart Policy #####
      restart_policy:
        condition: on-failure # Ensures service restarts only if it crashes.
        delay: 5s # Waits 5 seconds before attempting a restart.
        max_attempts: 3 # Limits restart attempts to prevent infinite loops.

    ##### Resource Constraints #####
      resources:
        limits:
          cpus: "1.00" # Restricts CPU usage to prevent excessive consumption.
          memory: "2G" # Caps memory usage at 2GB per instance.
        reservations:
          cpus: "0.50" # Guarantees a minimum of 50% CPU availability.
          memory: "1G" # Ensures a baseline 1GB memory allocation for stability.

##### Network Definitions #####
networks:
  traefik-public:
    external: true # Uses an externally created Traefik network for reverse proxy management.
