version: '3'

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
  #    ADVERTISE_IP: ${swarm_ip}:32400
      PLEX_CLAIM: ${claim}
      TZ: ${TZ}
    volumes:
      - ${config}/plex:/config
      - ${config}/plex/plex_transcode:/transcode
      - ${media}:/data
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.plex.rule=Host(`plexswarm`)"
        - 'traefik.http.routers.lidarr.entrypoints=web'
        - "traefik.http.services.plex.loadbalancer.server.port=32400"
        - homepage.group=Servarr
        - homepage.name=plex
        - homepage.icon=plex.png
        - homepage.href=http://plexswarm
        - homepage.description=viewer
networks:
  traefik-public:
    external: true




