version: "3.7" # Specifies the Docker Compose file format.

services:

  ##### Define the IT-Tools Service #####
  homepage:
    image: corentinth/it-tools:latest # Uses the latest IT-Tools image from GitHub Container Registry.
    container_name: It\T-Tools # Defines a custom container name for easier identification.

    ##### Port Mapping #####
    ports:
      - 8082:80 # Maps container port 80 to host port 8082 for external access.

    ##### Network Configuration #####
    networks:
      - traefik-public # Connects service to Traefik reverse proxy for efficient routing.

    ##### Deployment Configuration #####
    deploy:
      labels:
        # Traefik reverse proxy settings for DNS resolution and routing
        - traefik.enable=true # Enables Traefik routing for this service.
        - traefik.http.routers.tools.rule=Host(`tools`) # Defines hostname routing within the network.
        - traefik.http.routers.tools.entrypoints=web # Uses HTTP entrypoint (consider securing with HTTPS).
        - traefik.http.services.tools.loadbalancer.server.port=80 # Specifies the service port within Traefik.

        # Homepage dashboard integration for easy service discovery
        - homepage.group=Utilities # Groups IT-Tools under 'Utilities' for better organization.
        - homepage.name=IT-Tools # Sets display name for accessibility.
        - homepage.icon=it-tools.svg # Assigns a recognizable icon for the dashboard.
        - homepage.href=http://tools/ # Provides direct access via the homepage dashboard.
        - homepage.description=Handy tools # Brief description of the service.
        - "shepherd.watch=true"

        # Enable automatic updates with Watchtower
        - com.centurylinklabs.watchtower.enable="true" # Allows Watchtower to manage automatic updates.

##### Network Definitions #####
networks:
  traefik-public:
    external: true # Uses an externally created Traefik network for reverse proxying and service communication.
