services:
  app:
    image: filebrowser/filebrowser:latest
    volumes:
      # Base scope of filebrowser access on your server:
      - /mnt/docker-storage/filebrowser/config:/srv 
      - /mnt/docker-storage/filebrowser/config.json:/etc/config.json
      - /mnt/docker-storage/filebrowser/database:/etc/database.db
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true   #enable the use of traefik labels for routing.
        - traefik.http.routers.file.rule=Host(`filebrowser`)   #local dns setting
        - traefik.http.routers.file.entrypoints=web
        - traefik.http.services.file.loadbalancer.server.port=81   #tells Traefik which port to route to for this app.
       
        #homepage labels when autodiscovering docker swarm services.
        - homepage.group=Servarr
        - homepage.name=filebrowser
        - homepage.icon=filebrowser.png
        - homepage.href=http://filebrowser
        - homepage.description=filebrowser
networks:
networks:
  traefik_public:
    external: true
