services:
  app:
    image: filebrowser/filebrowser:latest
    volumes:
      - /mnt/docker-storage/filebrowser/home:/srv #Change to match your directory
      - /mnt/docker-storage/filebrowser/filebrowser.db:/database/filebrowser.db #Change to ma>
      - /mnt/docker-storage/filebrowser/settings.json:/config/settings.json #Change to match >

    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8095:80 #Change the port if needed
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true   #enable the use of traefik labels for routing.
        - traefik.http.routers.file.rule=Host(`filebrowser`)   #local dns setting
        - traefik.http.routers.file.entrypoints=web
        - traefik.http.services.file.loadbalancer.server.port=8093   #tells Traefik which port to route to for this app.
       
        #homepage labels when autodiscovering docker swarm services.
        - homepage.group=Servarr
        - homepage.name=filebrowser
        - homepage.icon=filebrowser.png
        - homepage.href=http://filebrowser
        - homepage.description=filebrowser
networks:
networks:
  traefik-public:
    external: true
