version: "3"
services:
  ...
  shepherd:
    build: .
    image: containrrr/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
deploy:
    mode: global
    placement: 
        constraints: 
            - node.hostname == node3
    restart_policy:
        condition: on-failure
   ##### Homepage Dashboard Labels #####
   labels:
     - homepage.group=System Tools # Groups Watchtower under "System Tools" in the dashboard.
     - homepage.name=Shephard # Sets display name for easy identification.
     - homepage.icon=shephard.png # Assigns a recognizable icon.
     - homepage.description=Auto-update Docker containers # Short service description.
