version: "3"
services:
  shepherd:
    image: containrrr/shepherd
    env_file : /mnt/docker-storage/shepherd/shepherd.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      placement: 
        constraints: 
            - node.hostname == node3
      restart_policy:
        condition: on-failure
   ##### Homepage Dashboard Labels #####
      labels:
        - homepage.group=System Tools # Groups Watchtower under "System Tools" in the dashboard.
        - homepage.name=Shephard # Sets display name for easy identification.
        - homepage.icon=https://avatars.githubusercontent.com/u/49166261?v=4 # Assigns a recognizable icon.
        - homepage.description=Auto-update Docker containers # Short service description.
