version: '3.8'

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole
    ports:
      - target: 53
        published: 53
        protocol: tcp
        mode: host
      - target: 53
        published: 53
        protocol: udp
        mode: host
        mode: host
    environment:
      TZ: 'America/Vancouver'
     # WEBPASSWORD: 'foobar2000'
    # Volumes store your data between container upgrades
    volumes:
      - /mnt/docker-storage/pihole/pihole-data:/etc/pihole/
      - /mnt/docker-storage/pihole/pihole-dnsmasq:/etc/dnsmasq.d/

    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    networks:
      - pihole
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik-public'
        - 'traefik.http.routers.pihole.rule=Host(`pihole`)'
        - 'traefik.http.routers.pihole.tls=true'
        - 'traefik.http.routers.pihole.tls.certresolver=myresolver'
        - 'traefik.http.services.pihole-srv.loadbalancer.server.port=67'
        - homepage.group=Servarr
        - homepage.name=PiHole
        - homepage.icon=pihole.png
        - homepage.href=http://pihole
        - homepage.description=DNS

networks:
  pihole:
  traefik-public:
    external: true
