services:
  pihole:
    image: pihole/pihole
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == node2]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=traefik-public'
        - 'traefik.http.routers.pihole.rule=Host(`pihole`)'
        - 'traefik.http.routers.pihole.tls=true'
        - 'traefik.http.routers.pihole.tls.certresolver=myresolver'
        - 'traefik.http.services.pihole-srv.loadbalancer.server.port=81'
        - homepage.group=Servarr
        - homepage.name=PiHole
        - homepage.icon=pihole.png
        - homepage.href=http://pihole
        - homepage.description=DNS
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"
    environment:
      TZ: 'America/Vancouver'
      WEBPASSWORD: 'Hurts2p33'
      # this supposedly reverts to previous behaviour to support cap_add
      FTL_CMD: 'debug'
      DNSMASQ_LISTENING: 'all'
    volumes:
      - /mnt/docker-storage/pihole/pihole-data:/etc/pihole/
      - /mnt/docker-storage/pihole/pihole-dnsmasq:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 9.9.9.9

    networks:
      - pihole
      - traefik-public

networks:
  pihole:
  traefik-public:
    external: true
