version: "3.9"

services:
  broker:
    image: redis:latest
    volumes:
      - redisdata:/data
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]

  db:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
    volumes:
      - dbdata:/var/lib/mysql
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    ports:
      - "8005:8000"
    volumes:
      - /mnt/docker-storage/paperlessng/data:/usr/src/paperless/data
      - /mnt/nfs/data/files:/usr/src/paperless/media
      - /mnt/docker-storage/paperlessng/export:/usr/src/paperless/export
      - /mnt/docker-storage/paperlessng/consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: paperless
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints: [node.role == manager]
      labels:
        - homepage.group=Productivity
        - homepage.name=PaperlessNGX
        - homepage.icon=paperless.png
        - homepage.href=http://10.0.0.20:8005/
        - homepage.description=e-paper management tool
        - com.centurylinklabs.watchtower.enable=true

  gotenberg:
    image: gotenberg/gotenberg:latest
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    deploy:
      restart_policy:
        condition: any

  tika:
    image: apache/tika:latest
    deploy:
      restart_policy:
        condition: any

volumes:
  redisdata:
  dbdata:
