version: '3.8'

services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.swarmMode=true"
      - "--accesslog=true"
      - "--log.level=DEBUG"
      - "--log.format=json"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.enable: "false"
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
