services:
  traefik:
    image: traefik:latest
    hostname: '{{.Node.Hostname}}'
    ports:
      # listen on host ports without ingress network
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik_config:/etc/traefik
    command:
      - --api.dashboard=true
      - --log.level=DEBUG
      - --accesslog=true
      - --providers.swarm.exposedByDefault=true
      - --providers.swarm.network=traefik-public
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - --entrypoints.web.address=:80

    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == node1
      labels:
        - traefik.enable=true
        - traefik.http.routers.mydashboard.rule=Host(`traefik`)
        - traefik.http.routers.mydashboard.service=api@internal
        - traefik.http.services.mydashboard.loadbalancer.server.port=1337
        - homepage.group=System Tools
        - homepage.name=Traefik
        - homepage.icon=traefik.png
        - homepage.href=http://traefik/
        - homepage.description= proxy
        - "shepherd.watch=true"

  whoami:
    image: traefik/whoami:latest
    hostname: '{{.Node.Hostname}}'
    networks:
      - traefik-public
    deploy:
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.whoami.rule=Host(`whoami`)
        - traefik.http.services.whoami.loadbalancer.server.port=80
volumes:
  traefik_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker-storage/traefik
networks:
 traefik-public:
  external: true
