version: "3.9"

services:
  traefik:
    image: traefik:v2.9
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=stevenfmeyer@me.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    secrets:
      - TUNNEL_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker-storage/traefik/lets:/letsencrypt
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/TUNNEL_TOKEN
    networks:
      - traefik-public
    deploy:
      placement:
        constraints:
          - node.role == manager
secrets:
  TUNNEL_TOKEN:
    external: true
networks:
  traefik-public:
    external: true
