services:
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    ports: 
      - 8086:8080
    deploy:  
      labels:
        #homepage labels when autodiscovering docker swarm services.
        - homepage.group=Productivity
        - homepage.name=Drawio
        - homepage.icon=draw-io.svg
        - homepage.href=http://10.0.0.20:8086/
        - homepage.description=drawing tool
        - com.centurylinklabs.watchtower.enable: "true"
    networks:
      - traefik-public
    restart: always
networks:
  traefik-public:
    external: true
