version: "3.7"

services:
  drawio:
    image: jgraph/drawio:latest
    ports:
      - 8086:80
    volumes:  
      - ${config}/drawio:/drawio/
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true   #enable the use of traefik labels for routing.
        - traefik.http.routers.drawio.rule=Host(`drawio`)   #local dns setting
        - traefik.http.routers.drawio.entrypoints=web
        - traefik.http.services.drawio.loadbalancer.server.port=8086   #tells Traefik which port to route to for this app.
       
        #homepage labels when autodiscovering docker swarm services.
        - homepage.group=Servarr
        - homepage.name=drawio
        - homepage.icon=drawio.png
        - homepage.href=http://10.0.0.20:8086/
        - homepage.description=drawing tool
networks:
  traefik-public:
    external: true

