services:
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    ports: 
      - 8086:8080
    deploy:  
      labels:
        #homepage labels when autodiscovering docker swarm services.
        - homepage.group=Servarr
        - homepage.name=drawio
        - homepage.icon=drawio.png
        - homepage.href=http://10.0.0.20:8086/
        - homepage.description=drawing tool
    networks:
      - traefik-public
    restart: always
networks:
  traefik-public:
    external: true
