version: "3.9" # Specifies the Docker Compose file format.

services:

  ##### Define the Radarr Movie Management Service #####
  radarr:
    image: lscr.io/linuxserver/radarr:latest # Uses the latest Radarr image from LinuxServer.io.

    ##### Environment Configuration #####
    environment:
      - PUID=${PUID} # Sets user ID for file permissions.
      - PGID=${PGID} # Defines group ID to ensure proper access.
      - TZ=${TZ} # Configures the timezone for consistent scheduling.

    ##### Persistent Storage Configuration #####
    volumes:
      - /etc/localtime:/etc/localtime:ro # Syncs container time with the host to prevent scheduling issues.
      - ${config}/radarr:/config # Stores configuration files persistently.
      - ${media}/movies:/movies # (Optional) Mounts media storage—ensure proper permissions.
      - ${data}:/data # Defines general persistent storage.

    ##### Port Mapping #####
    ports:
      - "7878:7878" # Maps container port 7878 to host port 7878 for external access.

    ##### Network Configuration #####
    networks:
      - traefik-public # Connects Radarr to the Traefik reverse proxy for routing.

    ##### Deployment Configuration #####
    deploy:
      ##### Reverse Proxy Labels for Traefik #####
      labels:
        - "traefik.enable=true" # Enables Traefik service routing.
        - "traefik.http.routers.radarr.rule=Host(`radarr`)" # Uses hostname-based routing—update as needed.
        - "traefik.http.services.radarr.loadbalancer.server.port=7878" # Specifies service port for Traefik load balancing.
        - "traefik.http.routers.radarr.entrypoints=web" # Uses HTTP entrypoint—consider HTTPS for security.

      ##### Homepage Dashboard Labels #####
        - "homepage.group=Media" # Groups Radarr under "Media" in the dashboard.
        - "homepage.name=Radarr" # Sets display name for easy identification.
        - "homepage.icon=radarr.png" # Assigns a recognizable icon.
        - "homepage.href=http://radarr/" # Provides direct access via the dashboard.
        - "homepage.description=Movies" # Short description for dashboard entry.
        - "homepage.weight=2" # Defines weight for ordering in the dashboard.

      ##### Automated Updates #####
        - "com.centurylinklabs.watchtower.enable=true" # Enables automatic updates via Watchtower.

##### Network Definitions #####
networks:
  traefik-public:
    external: true # Uses an externally created Traefik network for reverse proxy management.
