services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-storage/radarr:/config
      - /mnt/nfs/data/movies:/movies
      - /mnt/nfs/torrents:/data
    restart: unless-stopped
    ports:
      - 7878:7878
    networks:
      - traefik-public
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.radarr.rule=Host(`radarr`)'
        - 'traefik.http.services.radarr.loadbalancer.server.port=7878'
        - 'traefik.http.routers.radarr.entrypoints=web'
        - homepage.group=Servarr
        - homepage.name=Radarr
        - homepage.icon=radarr.png
        - homepage.instance.internal.href=http://radarr
        - homepage.description=Movies
networks:
  traefik-public:
    external: true


