version: "3.7"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3005:3000
    volumes:
      - ${config}/homepage:/app/config
      - ${data}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true   #enable the use of traefik labels for routing.
        - traefik.http.routers.homepage.rule=Host(`homepage`)   #local dns setting
        - traefik.http.routers.homepage.entrypoints=web
        - traefik.http.services.homepage.loadbalancer.server.port=3000   #tells Traefik which port to route to for this app.
       
        #homepage labels when autodiscovering docker swarm services.
        - homepage.group=Utilities
        - homepage.name=HomePage
        - homepage.icon=homepage.png
        - homepage.href=http://homepage
        - homepage.description=dashboard
        - com.centurylinklabs.watchtower.enable: "true"
networks:
  traefik-public:
    external: true
