version: "3.7"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /mnt/docker-storage/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.homepage.rule=Host(`homepage`)
        - traefik.http.routers.homepage.entrypoints=web
        - traefik.http.services.homepage.loadbalancer.server.port=3000
        - homepage.group=Servarr
        - homepage.name=HomePage
        - homepage.icon=homepage.png
        - homepage.href=http://homepage
        - homepage.description=dashboard
networks:
  traefik-public:
    external: true
