version: "3.7"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3005:3000
    volumes:
      - /mnt/docker-storage/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.homepage.rule=Host(`homepage`)
        - traefik.http.routers.homepage.entrypoints=web
        - traefik.http.services.homepage.loadbalancer.server.port=3005
networks:
  traefik-public:
    external: true



