version: "3.9"

services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    deploy:
      mode: replicated
      replicas: 1 # Specify replicas for high availability
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      labels:
        # Traefik labels for routing
        - traefik.enable=true
        - traefik.http.routers.homepage.rule=Host(`homepage`) # Replace with your domain
        - traefik.http.routers.homepage.entrypoints=web
        - traefik.http.services.homepage.loadbalancer.server.port=3000
        # Homepage autodiscovery labels
        - homepage.group=Utilities
        - homepage.name=HomePage
        - homepage.icon=homepage.png
        - homepage.href=http://homepage.example.com
        - homepage.description=Dashboard
        - com.centurylinklabs.watchtower.enable="true"
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    ports:
      - "3005:3000"
    volumes:
      - /mnt/docker-storage/homepage/config:/app/config:rw # Persistent storage with read-only for added security
      - /mnt/docker-storage/homepage/data:/data:rw # Ensure appropriate access
      - /var/run/docker.sock:/var/run/docker.sock:ro # Keep the socket read-only
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true

