# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settin
title: Bobo Homepage
background:
  image: https://unsplash.com/photos/a-mountain-range-with-a-lake-in-the-foreground-T_Qe4QlMIvQ
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100
theme: dark
color: slate
<div id="ww_b7bcf16540fab" v='1.3' loc='id' a='{"t":"horizontal","lang":"en","sl_lpl":1,"ids":[],"font":"Arial","sl_ics":"one_a","sl_sot":"celsius","cl_bkg":"image","cl_font":"#FFFFFF","cl_cloud":"#FFF>

statusStyle: "basic"
hideVersion: true
layout:
  Hosting:
    tab: First
    style: row
    columns: 3
    icon: mdi-folder-multiple-image

  Servarr:
    tab: First
    style: row
    columns: 5
    icon: mdi-server
  proxmox:
    tab: Second

  Build:
    tab: Second
  web hosting:
    tab: Second
  cool reference:
    tab: Second




