---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
#<div id="ww_b7bcf16540fab" v='1.3' loc='id' a='{"t":"horizontal","lang":"en","sl_lpl":1,"ids":[],"font":"Arial","sl_ics":"one_a","sl_sot":"celsius","cl_bkg":"image","cl_font":"#FFFFFF","cl_cloud":"#FF>

- Hosting:
    - Proxmox:
        icon: proxmox.png
        href: https://proxmox:8006
        ping: https://proxmox:8006
        description: proxmox host
        widget:
          type: proxmox
          url: https://proxmox:8006
          username: api1@pam!homepage
          password: 6e301f48-ad45-4d4e-8e15-d1ebecc577c6
          node: george # optional
    - transmission:
       icon: transmission.png
       href: http://swarm:9091
       ping: http://swarm:9091
       description: downloader
       widget:
        type: transmission
        url: http://swarm:9091

    - HomeAssistant:
        icon: home-assistant.png
        href: http://assist:8123
        ping: http://assist:8123
        description: home automation
        widget:
          type: homeassistant
          url: http://assist:8123
          key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIyMTBhYTJlYjE0NDI0NjNmYTExODk4NmI4ZmYzNGE2YyIsImlhdCI6MTczODQzMTgxNCwiZXhwIjoyMDUzNzkxODE0fQ.R3g5_M6s1gpgr6uOaNUfi3_ykwJT_IrdU6YLzGCi-ts
          custom:
#            - state: sensor.total_power
#            - state: sensor.total_energy_today
#              label: energy today
            - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
              label: switches on
            - state: weather.forecast_home
              label: temperature
              value: "{attributes.temperature} {attributes.temperature_unit}"
#              label: wind speed
 #             value: "{attributes.wind_speed} {attributes.wind_speed_unit}"
    - Proxmox backup:
        icon: proxmox.png
        href: https://backup:8007
        ping: https://backup:8007
        description: backup server

    - NAS:
       icon: webmin.png
       href: https://nas:12321
       ping : https:/nas
       description: NAS management gui
    - PiHole:
        icon: pi-hole.png
        ping: http://pihole/admin
        href: http://pihole/admin
        description: dns management
#        widget:
#          type: pihole
#          url: http://10.0.0.4
#          version: 5 # required if running v6 or higher, defaults to 5
#          key: 197c257b0324c3cb6039773708c67f45bcc0d12ca96e6a7e57bb33e19a197daf # optional, in v6 can be your >   

