version: '3.7'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: --interval 30 --label-enable
    deploy:
      placement:
        constraints: [node.hostname == node1]
      labels:  
        - homepage.group=System Tools
        - homepage.name=Watchtower
        - homepage.icon=watchtower.png
        - homepage.description=autoupdate docker


