version: "3.7" # Specifies the Docker Compose file format version.

services:

  ##### Define the Watchtower Auto-Update Service #####
  watchtower:
    image: containrrr/watchtower # Uses the official Watchtower image for automated container updates.

    ##### Persistent Storage Configuration #####
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Provides read-only access to the Docker socket for monitoring running containers.

    ##### Update Interval & Label-Based Targeting #####
    command: --interval 30 --label-enable # Sets auto-update interval (30 seconds) and enables label-based updates.

    ##### Deployment Configuration #####
    deploy:
      ##### Service Placement Constraints #####
      placement:
        constraints: [node.hostname == node1] # Ensures Watchtower runs specifically on node1—modify based on infrastructure.

      ##### Homepage Dashboard Labels #####
      labels:
        - homepage.group=System Tools # Groups Watchtower under "System Tools" in the dashboard.
        - homepage.name=Watchtower # Sets display name for easy identification.
        - homepage.icon=watchtower.png # Assigns a recognizable icon.
        - homepage.description=Auto-update Docker containers # Short service description.

##### Best Practice Considerations #####
# ✅ Consider fine-tuning update interval—30 seconds might be too frequent for production environments.
# ✅ Ensure label-based targeting is necessary—updating all containers automatically may cause unintended disruptions.
# ✅ Use external monitoring tools alongside Watchtower for controlled container lifecycle management.

