version: "3.4"
services:
  ghost:
    image: ghost:5
    environment:
      url: https://stevenfmeyer.me
      database__client: mysql
      database__connection__host: mysqldbhost
      database__connection__user: root
      database__connection__password: supersecurep4sswo0rdhereCanBeRpelaceByYOu
      database__connection__database: ghost
    volumes:
      - content:/var/lib/ghost/content
    networks:
      - traefik-public
      - default
    deploy:
      placement:
        constraints:
          - node.labels.blog == true
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.blog.rule=Host(steven}
        - traefik.http.routers.blog.entrypoints=http

  db:
    image: mysql:8.0
    restart: always
    networks:
      - default
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecurep4sswo0rdhereCanBeRpelaceByYOu
    deploy:
      placement:
        constraints:
          - node.labels.blog == true 
volumes:
  content:

networks:
  traefik-public:
    external: true
  default:
    external: false

