services:
  ghost:
    image: ghost:5
    ports:
      - "2368:2368"
    networks:
      - traefik-public
      - default
    volumes:
      - content:/var/lib/ghost/content
    environment:
      url: https://stevenfmeyer.me
      database__client: mysql
      database__connection__host: mysqldbhost
      database__connection__user: root
      database__connection__password: supersecurep4sswo0rdhereCanBeRpelaceByYOu
      database__connection__database: ghost
    deploy:
      placement:
        constraints:
          - node.labels.blog == true
      labels:
        - homepage.group=Servarr
        - homepage.name=Ghost
        - homepage.icon=ghost.png
        - homepage.href=http://stevenfmeyer.me
        - homepage.description=blog
      replicas: 1
    depends_on:
      - mysql
  db:
    image: mysql:8.0
    networks:
      - default
    volumes:
      - content:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecurep4sswo0rdhereCanBeRpelaceByYOu
    deploy:
      placement:
        constraints:
          - node.labels.blog == true 
volumes:
  content:


networks:
  backend-net:
    external: true
  frontend-net:
    external: true
