version: "3.4"
services:

  mysql:
    image: mysql:latest
    networks:
      - default
    volumes:
      - ${config}/ghost/sql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${groot_pswrd}
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ${gpswrd}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  ghost:
    image: ghost:5
    environment:
      url: http://blog
      database__client: mysql
      database__connection__host: mysql:3306
      database__connection__user: ghost
      database__connection__password: ${gpswrd}
      database__connection__database: ghost
    volumes:
      - ${config}/ghost:/var/lib/ghost/content
    networks:
      - traefik-public
      - default
    deploy:
      labels:
        - 'homepage.group=Servarr'
        - 'homepage.name=ghost'
        - 'homepage.icon=ghost.png'
        - 'homepage.href=http://blog/'
        - 'homepage.description=blog'

networks:
  traefik-public:
    external: true
  default:
    external: false

