
version: '3.3'
services:
  ghost:
    image: ghost:latest
    environment:
      database__client: mysql
      database__connection__database: ghostdb
      database__connection__host: mysql.local
      database__connection__password: ${ghostpass}
      database__connection__user: mysqluserx
      url: http://blog
    ports:
     - 2368:2368
    volumes:
     - ${config}/ghost:/var/lib/ghost/content
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 1
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.blog.rule=Host(`blog`)'
        - 'traefik.http.services.blog.loadbalancer.server.port=2368'
        - 'traefik.http.routers.blog.entrypoints=web'
        - 'homepage.group=Servarr'
        - 'homepage.name=ghost'
        - 'homepage.icon=ghost.png'
        - 'homepage.href=http://blog/'
        - 'homepage.description=blog'
networks:
  traefik-public:
    external: true
