version: '3.8'
services:
  mysql:
    image: mysql:latest
    networks:
      - backend-ntwk
    volumes:
      - ${config}/wordpress/sql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${wproot_pswrd}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${wppswrd}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    networks:
      - frontend-ntwk
      - backend-ntwk
    volumes:
      - ${config}/wordpress:/data
      - ${media}/files:/files
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${wppswrd}
      WORDPRESS_DB_NAME: wordpress
    deploy:
      labels:
        - homepage.group=Servarr
        - homepage.name=wordpress
        - homepage.icon=wordpress.png
        - homepage.href=http://stevenfmeyer.me
        - homepage.description=blog
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql

volumes:
  sql-data:

networks:
  backend-ntwk:
    external: true
  frontend-ntwk:
    external: true
