version: "3.9"
services:
  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run
    deploy:
      replicas: 2
    networks:
      - frontend-ntwk
    environment:
      - TUNNEL_TOKEN=${token}

networks:
    frontend-ntwk:
      external: true
