services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_MODE=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${config}/dozzle:/config
    ports:
      - 8083:8080
    networks:
      - dozzle
      - traefik-public
    deploy:
      mode: global
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.dozzle.rule=Host(`monitor`)'
        - 'traefik.http.services.dozzle.loadbalancer.server.port=8083'
        - 'traefik.http.routers.dozzle.entrypoints=web'
        - homepage.group=Monitoring
        - homepage.name=Dozzle
        - homepage.icon=https://developer.asustor.com/uploadIcons/0020_117518_1660879946_dozzle_256.png
        - homepage.href=http://swarm:8083
        - homepage.description=stats
networks:
  traefik-public:
    external: true
  dozzle:
    driver: overlay
