version: "3.9"

services:
  dozzle:
    image: amir20/dozzle:latest # Pin the version if necessary
    environment:
      - DOZZLE_MODE=swarm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${config}/dozzle:/config:rw
    ports:
      - "8083:8080"
    networks:
      - traefik-public
    deploy:
      mode: global
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.dozzle.rule=Host(`dozzle`)' # Use proper FQDN
        - 'traefik.http.services.dozzle.loadbalancer.server.port=8080'
        - 'traefik.http.routers.dozzle.entrypoints=web'
        - homepage.group=System Tools
        - homepage.name=Dozzle
        - homepage.icon=https://developer.asustor.com/uploadIcons/0020_117518_1660879946_dozzle_256.png
        - homepage.href=http://dozzle/
        - homepage.description=Stats
        - com.centurylinklabs.watchtower.enable="true"
      resources:
        limits:
          cpus: "0.50"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik-public:
    external: true
