version: '3.2' # Specifies the Docker Compose file format version.

services:

  ##### Define the Portainer Agent #####
  agent:
    image: portainer/agent:latest # Uses the latest Portainer agent image to facilitate remote management.

    ##### Persistent Storage Configuration #####
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Provides read-only access to the Docker socket for container monitoring.
      - /var/lib/docker/volumes:/var/lib/docker/volumes # Maps Docker volumes to allow management by Portainer.

    ##### Network Configuration #####
    networks:
      - portainer_agent_network # Connects the agent to the Portainer network for communication.

    ##### Deployment Configuration #####
    deploy:
      mode: global # Ensures the service runs on all nodes in the Swarm.
      placement:
        constraints: [node.platform.os == linux] # Restricts deployment to Linux-based nodes.

  ##### Define the Portainer CE Management Service #####
  portainer:
    image: portainer/portainer-ce:latest # Uses the latest Community Edition of Portainer for managing containers.

    ##### Command Configuration #####
    command: -H tcp://tasks.agent:9001 --tlsskipverify # Connects to the agent via TCP while skipping TLS verification.

    ##### Port Mapping #####
    ports:
      - "9443:9443" # Secure HTTPS access to the Portainer UI
