services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker-storage/lidarr:/config
      - /mnt/nfs/data/music:/music
      - /mnt/nfs/torrents:/data
    ports:
      - 8686:8686
    restart: unless-stopped

    networks:
      - traefik-public
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.lidarr.rule=Host(`lidarr`)'
        - 'traefik.http.services.lidarr.loadbalancer.server.port=8686'
        - 'traefik.http.routers.lidarr.entrypoints=web'
        - homepage.group=Servarr
        - homepage.name=Lidarr
        - homepage.icon=lidarr.png
        - homepage.href=http://lidarr
        - homepage.description=music
networks:
  traefik-public:
    external: true



