version: "3.8"

services:

  ghost-db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghostuser
      MYSQL_PASSWORD_file: /run/secrets/db_password

    secrets:
      - db_root_password # References externally stored root password secret.
      - db_password  
    volumes:
      - ghost_db_data:/var/lib/mysql
    networks:
      - ghost-net
    deploy:
      placement:
        constraints: [node.hostname == node1]

  ghost:
    image: ghost:5-alpine
    environment:
      url: http://10.0.0.20:2368
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ghostuser
      database__connection__password_file: /run/secrets/db_password
      database__connection__database: ghost
    depends_on:
      - ghost-db
    
    secrets:
      - db_root_password # References externally stored root password secret.
      - db_password
    volumes:
      - ghost_content:/var/lib/ghost/content
    networks:
      - ghost-net
    ports:
      - target: 2368
        published: 2368
        protocol: tcp
        mode: host # Bind directly to 10.0.0.20:2368
    deploy:
      placement:
        constraints: [node.hostname == node1] # Adjust this to match the hostname of the node with IP 10.0.0.20
      restart_policy:
        condition: on-failure

volumes:
  ghost_db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker-storage/ghost/db-data
  
  ghost_content:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker-storage/ghost

secrets:
  db_password:
    external: true # Retrieves the database password from an external secret manager.
  db_root_password:
    external: true 
networks:
  ghost-net:
    driver: overlay
