version: "3.8"

services:

  ghost-db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: ghostrootpass
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghostuser
      MYSQL_PASSWORD: ghostpass
    volumes:
      - /mnt/docker-storage/ghost/db-data:/var/lib/mysql
    networks:
      - ghost-net
    deploy:
      placement:
        constraints: [node.hostname == node1]

  ghost:
    image: ghost:5-alpine
    environment:
      url: http://10.0.0.20:2368
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: ghostuser
      database__connection__password: ghostpass
      database__connection__database: ghost
    depends_on:
      - ghost-db
    volumes:
      - /mnt/docker-storage/ghost:/var/lib/ghost/content
    networks:
      - ghost-net
    ports:
      - target: 2368
        published: 2368
        protocol: tcp
        mode: host # Bind directly to 10.0.0.20:2368
    deploy:
      placement:
        constraints: [node.hostname == node1] # Adjust this to match the hostname of the node with IP 10.0.0.20
      restart_policy:
        condition: on-failure

#volumes:
#  ghost_db_data:
#    driver: local
#  ghost_content:
#    driver: local

networks:
  ghost-net:
    driver: overlay
