services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    #logging:
    #  driver: json-file
    #  options:
    #    max-file: ${DOCKERLOGGING_MAXFILE}
    #    max-size: ${DOCKERLOGGING_MAXSIZE}
    user: 1000:1000
    environment:
      - TZ=${TZ}
    volumes:
      - ${config}/autobrr:/config
      - ${media}/tv:/tv
    ports:
      - 7474:7474
    networks:
      - traefik-public
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.autobrr.rule=Host(`autobrr`)'
        - 'traefik.http.services.autobrr.loadbalancer.server.port=7474'
        - 'traefik.http.routers.autobrr.entrypoints=web'
        - 'homepage.group=Servarr'
        - 'homepage.name=autobrr'
        - 'homepage.icon=autobrr.png'
        - 'homepage.href=http://autobrr/'
        - 'homepage.description=download assistant'
networks:
  traefik-public:
    external: true
