services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    volumes:
      - /mnt/nfs/torrents:/data
      - /mnt/docker-storage/tansmission:/config
    environment:
      - OPENVPN_PROVIDER=NordVPN
      - OPENVPN_CONFIG=ca1688.nordvpn.com
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - LOCAL_NETWORK=10.0.0.0/24
    logging:
      driver: json-file
      options:
         max-size: 10m
    image: haugene/transmission-openvpn
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.transmission.rule=Host(`transmission`)'
      - 'traefik.http.services.transmission.loadbalancer.server.port=9091'
      - 'traefik.http.routers.transmission.entrypoints=web'
      - homepage.group=Servarr
      - homepage.name=transmission
      - homepage.icon=transmission.png
      - homepage.href=http://transmission/
      - homepage.description=downloader-vpn
