services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    volumes:
      - ${data}:/data
      - ${config}/transmission:/config
    environment:
      - OPENVPN_PROVIDER=NordVPN
      - OPENVPN_CONFIG=${vpnconfig}
      - OPENVPN_USERNAME=${vpnuser}
      - OPENVPN_PASSWORD=${vpnpass}
      - LOCAL_NETWORK=${local}
    logging:
      driver: json-file
      options:
         max-size: 10m
    image: haugene/transmission-openvpn
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.transmission.rule=Host(`transmission`)'
      - 'traefik.http.services.transmission.loadbalancer.server.port=9091'
      - 'traefik.http.routers.transmission.entrypoints=web'
      - homepage.group=Media
      - homepage.name=transmission
      - homepage.icon=transmission.png
      - homepage.href=http://transmission/
      - homepage.description=downloader-vpn
      - homepage.weight=5
