services:
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    ports:
      - 9091:9091
    volumes:
      - /mnt/nfs/torrents:/data
      - /mnt/docker-storage/tansmission:/config
    environment:
      - OPENVPN_PROVIDER=NordVPN
      - OPENVPN_CONFIG=ca1688.nordvpn.com
      - OPENVPN_USERNAME=
      - OPENVPN_PASSWORD=
      - LOCAL_NETWORK=10.0.0.0/24
    logging:
      driver: json-file
      options:
         max-size: 10m
    image: haugene/transmission-openvpn
