version: '3.7'

services:
  wishthis:
    container_name: wishthis
    restart: unless-stopped
    image: hiob/wishthis:stable
    ports:
      - 8088:80
    volumes:
      - ${config}/wish/config.php:/var/www/html/src/config/config.php
    networks:
      - traefik-public
    deploy:
      labels:
        - homepage.group=Servarr
        - homepage.name=wish
        - homepage.icon=https://raw.githubusercontent.com/wishthis/wishthis/develop/src/assets/img/logo-readme.svg
        - homepage.href=https://wish
        - homepage.description=mylist
      replicas: 1
      restart_policy:
        condition: on-failure
  networks:
  traefik-public:
    external: true
