version: '3.7'

services:
  wishthis:
    container_name: wishthis
    restart: unless-stopped
    image: hiob/wishthis:stable
    environment:
      - VIRTUAL_HOST=sub.domain.ext
    ports:
      - 8088:80
    volumes:
      - ${config}/wish/config.php:/var/www/html/src/config/config.php
    networks:
      - wishthis
    deploy:
      labels:
        - homepage.group=Servarr
        - homepage.name=wish
        - homepage.icon=https://raw.githubusercontent.com/wishthis/wishthis/develop/src/assets/img/logo-readme.svg
        - homepage.href=https://wish
        - homepage.description=mylist
      replicas: 1
      restart_policy:
        condition: on-failure

      
  mariadb:
    container_name: db
    restart: unless-stopped
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/wishroot
      MARIADB_DATABASE: databasename
      MARIADB_USER: username
      MARIADB_PASSWORD_FILE: /run/secrets/wishpass
    secrets:
      - wishroot
      - wishpass
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    volumes:
      - ${config}/wish/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - wishthis
secrets:
  wishroot:
    external: true
 wishpass:
   external: true

networks:
  wishthis:
    external: true
