version: '3.9'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_NAME: "npm"
    secrets:
      - db_password
    volumes:
      - /mnt/docker-storage/npm:/data
      - /mnt/docker-storage/npm/lets:/etc/letsencrypt
    networks:
      - npm-db
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "homepage.group=System Tools"
        - "homepage.name=Nginx Proxy Manager"
        - "homepage.icon=npm.png"
        - "homepage.href=https://proxy"
        - "homepage.description=Manage proxy configuration and SSL certificates"
        - homepage.weight=5

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    volumes:
      - /mnt/docker-storage/npm/data:/var/lib/mysql
    networks:
      - npm-db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  npm-db:
    name: npm-db
    attachable: true
  traefik-public:
    external: true

secrets:
   db_password:
     external: true
   db_root_password:
     external: true
